### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by ghost** [zamentur/ajaxgoogleapis_ynh#1]
What is the license (scripts, conf, manifest, etc)?

**Comment by zamentur** [comment]
Scripts, conf and manifest are under the MIT license or the GPLv3 license.
For the sources directory, each library has his own license.

**Comment by zamentur** [comment]
I reopen until I had the license in the package

**Comment by ghost** [comment]
"MIT license" is ambigous https://en.wikipedia.org/wiki/MIT_License#Various_versions https://directory.fsf.org/wiki/License:X11 https://directory.fsf.org/wiki/License:Expat

**Comment by zamentur** [comment]
Thanks
